### ISSUE TITLE
update platform to sifive

### ISSUE THREAD

**Issue by dylanmc** [martin-robert-fink/superBlink#2]
I got some warnings about the "riscv" platform being deprecated. Changing the platformio.ini file to the following fixed the project, and still runs great:

```
[env:hifive1]
platform = sifive
board = hifive1
framework = freedom-e-sdk
```

Thanks for the fantastic tutorial - it finally helped me get off the ground with my SiFive boards.

**Comment by ivankravets** [comment]
It should be fixed with https://github.com/martin-robert-fink/superBlink/pull/1

How did you get this outdated "riscv" project configuration?

**Comment by dylanmc** [comment]
> How did you get this outdated "riscv" project configuration?

a git clone of master, an hour or so ago. 

As an aside, I was super-pleased to see that 
```
[env:hifive1-revb]
platform = sifive
board = hifive1-revb
framework = freedom-e-sdk
``` 
works great with the RevB board too - yay!

**Comment by ivankravets** [comment]
Could you try again `git clone`? The PR #1 was merged 23 days ago. Did you install RISC-V dev/platform before?

**Comment by dylanmc** [comment]
Egads - you're right: that was one part I created by following along the instructions on YouTube, then imported the code from this repo from there. Whoops! #alreadyfixed
